---
- hosts: ansible
  gather_facts: no
  become: yes
  name: "Create cronjobs on the ansible server"
  tasks:
    - name: "transport cronjob for weekly updates of all LXCs and VMs"
      ansible.builtin.cron:
        user: transport
        name: "weekly updates"
        weekday: "0"
        hour: "3"
        minute: "30"
        job: /home/transport/ansible/cron-updates.sh > /dev/null 2>&1
