---
- hosts: websrv
  gather_facts: yes
  become: yes
  name: "Create cronjobs on webservers"
  tasks:
    - name: "gato cronjob for backups"
      ansible.builtin.cron:
        user: gato
        name: "backups"
        special_time: daily
        job: tar czf "/home/gato/backups/website-backup-$(date +\%Y-\%m-\%d).tgz" /home/gato/gatogatogato.ch-hugo > /dev/null 2> /dev/null

    - name: "gato cronjob for cleanup of backups"
      ansible.builtin.cron:
        user: gato
        name: "cleanup of backups"
        special_time: daily
        job: find /home/gato/backups/website-backup* -mtime +7 -type f -delete 2> /dev/null

    - name: "root cronjob for certbot renew"
      ansible.builtin.cron:
        user: root
        name: "certbot renew"
        special_time: weekly
        job: certbot renew --quiet
