---
- hosts: ansible
  gather_facts: no
  become: yes
  name: "Create cronjobs on the ansible server"
  tasks:
    - name: "transport cronjob for weekly updates of all LXCs and VMs"
      ansible.builtin.cron:
        user: transport
        name: "weekly updates"
        weekday: "0"
        hour: "3"
        minute: "30"
        job: /home/transport/ansible/cron-updates.sh > /dev/null 2>&1

    - name: "transport cronjob for the daily security updates of the hosts reachable from the internet"
      ansible.builtin.cron:
        user: transport
        name: "daily security updates"
        hour: "6"
        minute: "30"
        job: /home/transport/ansible/cron-run.sh security-updates > /dev/null 2>&1

    - name: "transport cronjob for the nightly mirror of all GitHub repos"
      ansible.builtin.cron:
        user: transport
        name: "git mirror"
        hour: "2"
        minute: "0"
        job: /home/transport/ansible/git-mirror.sh > /dev/null 2>&1

    - name: "transport cronjob for the weekly Proxmox host configuration backup"
      ansible.builtin.cron:
        user: transport
        name: "proxmox hostconfig backup"
        weekday: "0"
        hour: "5"
        minute: "0"
        job: /home/transport/ansible/cron-run.sh hostconfig-backup > /dev/null 2>&1

    - name: "transport cronjob for the daily Proxmox update reminder"
      ansible.builtin.cron:
        user: transport
        name: "proxmox update check"
        hour: "7"
        minute: "0"
        job: /home/transport/ansible/cron-run.sh updates-proxmox-check > /dev/null 2>&1
