---
- hosts: flickr
  gather_facts: yes
  become: yes
  name: "Create cronjobs on flickservers"
  tasks:
    - name: "gato cronjob for commenter"
      ansible.builtin.cron:
        user: gato
        minute: "00"
        hour: "08,12,13,15,17,19,20"
        name: "Start commenter every X hours"
        job: /home/gato/Apps/flickr-commenter/flickr-commenter.rb

    - name: "gato cronjob for preview pictures "
      ansible.builtin.cron:
        user: gato
        minute: "01,10,20,30,40,50"
        hour: "06-22"
        name: "Create new preview pictures"
        job: /home/gato/UPLOADS/uploader-scale-images.sh

    - name: "gato cronjob for nextcloud sync"
      ansible.builtin.cron:
        user: gato
        name: "nextcloud sync once"
        minute: "*/5"
        job: nextcloudcmd --silent --trust -n --path UPLOADS /home/gato/UPLOADS http://truenas.lan:30027

    - name: "gato cronjob for cleanup of log files"
      ansible.builtin.cron:
        user: gato
        name: "cleanup of log files"
        special_time: daily
        job: find /home/gato/Apps/flickr-commenter/logs/*.txt -mtime +7 -type f -delete 2> /dev/null

    - name: "gato cronjob for cleanup of old lock files 1"
      ansible.builtin.cron:
        user: gato
        name: "cleanup of old lock files 1"
        special_time: daily
        job: rm -f /home/gato/Apps/flickr-commenter/indexer.lock

    - name: "gato cronjob for cleanup of old lock files 2"
      ansible.builtin.cron:
        user: gato
        name: "cleanup of old lock files 2"
        special_time: reboot
        job: rm -f /home/gato/Apps/flickr-commenter/indexer.lock

    - name: "root cronjob for restart of dropbox service"
      ansible.builtin.cron:
        user: root
        name: "restart of dropbox service"
        special_time: daily
        job: systemctl restart dropbox.service
