---
- hosts: all
  gather_facts: yes
  become: yes
  name: "Install stuff on all servers"
  tasks:
    - name: "Install a list of packages"
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - avahi-daemon
        - ca-certificates
        - curl
        - debsums
        - git
        - gnupg-agent
        - locales
        - micro
        - mosh
        - mutt
        - net-tools
        - qemu-guest-agent
        - reboot-notifier
        - ruby
        - rubygems        
        - software-properties-common
        - sudo
        - sysvbanner
        - tmux
        - unzip
        - wget
        - zsh