---
- hosts: camsnaps
  gather_facts: yes
  become: yes
  name: "Install stuff on web servers"
  tasks:
    - name: "Install apt key"
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: F608A664B7DFFFEA

    - name: "Install a list of apt packages"
      ansible.builtin.apt:
        pkg:
        - apache2 
        - snapd
        - hugo
        - imagemagick
        - libimage-exiftool-perl
        - photish

    - name: "Enable the apache2 module rewrite"
      community.general.apache2_module:
        state: present
        name: rewrite

    - name: "Enable the apache2 module ssl"
      community.general.apache2_module:
        state: present
        name: ssl
