---
- hosts: flickrservers
  gather_facts: yes
  name: "Install stuff on flickr servers"
  tasks:
    - name: "Install a list of apt packages"
      become: yes
      ansible.builtin.apt:
        pkg:
        - exiftool
        - imagemagick

    - name: "Install ruby gem date"
      community.general.gem:
        name: date
        state: latest

    - name: "Install ruby gem flickr"
      community.general.gem:
        name: flickr
        state: latest

    - name: "Install ruby gem yaml"
      community.general.gem:
        name: yaml
        state: latest

    - name: "Install ruby gem yaml/store"
      community.general.gem:
        name: yaml/store
        state: latest

    - name: "Install ruby gem tempfile"
      community.general.gem:
        name: tempfile
        state: latest

    - name: "Install ruby gem json"
      community.general.gem:
        name: json
        state: latest

    - name: "Install ruby gem fileutils"
      community.general.gem:
        name: fileutils
        state: latest

    - name: "Install ruby gem mini_exiftool"
      community.general.gem:
        name: mini_exiftool
        state: latest

    - name: "Install ruby gem geocoder"
      community.general.gem:
        name: geocoder
        state: latest

    - name: "Install ruby gem htmlentities"
      community.general.gem:
        name: htmlentities
        state: latest
