---
- hosts: all
  gather_facts: yes
  become: yes
  name: "Create basic files on a new server"
  tasks:
    - name: "Create sudoers for gato"
      become: yes
      copy:
        dest: "/etc/sudoers.d/gato"
        content: |
          gato ALL=(ALL:ALL) NOPASSWD: /bin/su - transport
 
    - name: "Create sudoers file for transport"
      become: yes
      copy:
        dest: "/etc/sudoers.d/transport"
        content: |
          transport ALL=(ALL:ALL) NOPASSWD:ALL

    - name: "Delete /etc/motd"
      ansible.builtin.file:
        path: /etc/motd
        state: absent

    - name: "Find files in /etc/update-motd.d/"
      find:
        paths: /etc/update-motd.d/
        patterns: "*"
      register: files_to_delete

    - name: "Delete files in /etc/update-motd.d/"
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: "Create motd uname"
      become: yes
      copy:
        dest: "/etc/update-motd.d/10-uname"
        content: |
          #!/bin/sh
          uname -snvr

    - name: "Create motd gato"
      become: yes
      copy:
        dest: "/etc/update-motd.d/20-gato"
        content: |
          #!/bin/sh
          banner $(hostname | awk 'BEGIN { FS = "-" } ; { print $2 }')

    - name: "Set permissions for uname"
      file:
        path: "/etc/update-motd.d/10-uname"
        state: touch
        mode: u=rwx,g=rx,o=rx

    - name: "Set permissions for gato"
      file:
        path: "/etc/update-motd.d/20-gato"
        state: touch
        mode: u=rwx,g=rx,o=rx
