---
#- hosts: flickrservers,testservers,ansibleservers
- hosts: test1,test2,hercules,flickr,rclone
  gather_facts: true
  become: true
  name: "Shutdown nonproductive servers"
  tasks:
    - name: "Execute shutdown in 30s"
      community.general.shutdown:
        delay: 30

- hosts: ansible
  gather_facts: true
  become: true
  name: "Shutdown ansible server"
  tasks:
    - name: "Execute shutdown in 30s"
      community.general.shutdown:
        delay: 30
