---
- hosts: hercules,flickr
  # hercules is usually already off; don't report that as an error
  ignore_unreachable: true
  gather_facts: true
  become: true
  name: "Shutdown nonproductive servers"
  tasks:
    - name: "Execute shutdown in 30s"
      community.general.shutdown:
        delay: 30

- hosts: ansible
  gather_facts: true
  become: true
  name: "Shutdown ansible server"
  tasks:
    - name: "Execute shutdown in 30s"
      community.general.shutdown:
        delay: 30
