---
- hosts: flickrservers,testservers,ansibleservers
  gather_facts: true
  become: true
  name: "Shutdown nonproductive servers: flickrservers,testservers,ansibleservers"
  tasks:
    - name: "Execute shutdown in 30s"
      community.general.shutdown:
        delay: 30
