---
- import_playbook: find_reachable.yaml
  vars:
    target_group: debianservers

- hosts: reachable_debianservers
  gather_facts: yes
  become: yes
  name: "Debian: apt upgrade, one host at a time"
  tasks:
    - name: "Update apt repo and cache on all servers"
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      changed_when: false

    - name: "Upgrade all packages on all servers"
      become: true
      apt:
        upgrade: dist
        force_apt_get: yes
      throttle: 1

    - name: "Remove useless packages from the cache"
      ansible.builtin.apt:
        autoclean: yes

    - name: "Remove dependencies that are no longer required"
      ansible.builtin.apt:
        autoremove: yes

    - name: "Remove dependencies that are no longer required and purge their configuration files"
      ansible.builtin.apt:
        autoremove: yes
        purge: true

    - name: "Run the equivalent of apt-get clean as a separate step"
      apt:
        clean: yes
      changed_when: false

    - name: "Check if a reboot is needed"
      become: true
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
        get_checksum: no

    - name: "Reboot if kernel updated"
      become: true
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 15
        post_reboot_delay: 30
        test_command: uptime
      throttle: 1
      when: reboot_required_file.stat.exists
