---
- import_playbook: find_reachable.yaml
  vars:
    target_group: debianservers

- hosts: reachable_debianservers
  gather_facts: true
  become: true
  name: "Debian: update micro editor plugins"
  tasks:
    - name: "micro plugin update"
      become: true
      ansible.builtin.shell: micro --plugin update
      changed_when: false
