---
- import_playbook: find_reachable.yaml
  vars:
    target_group: debianservers

- hosts: reachable_debianservers
  gather_facts: yes
  become: yes
  name: "Update micro plugins"
  tasks:
    - name: "micro plugin update"
      become: true
      ansible.builtin.shell: micro --plugin update
