---
- hosts: piholeservers
  gather_facts: yes
  become: yes
  name: "Update pihole stuff"
  tasks:
    - name: "Update pihole core"
      ansible.builtin.command:
        cmd: pihole -up
      become: yes
      become_user: root
      
    - name: "Update pihole gravity"
      ansible.builtin.command:
        cmd: pihole -g
      become: yes
      become_user: root

    - name: "Reload lists"
      ansible.builtin.command:
        cmd: pihole restartdns reload
      become: yes
      become_user: root