---
- hosts: webservers
  gather_facts: yes
  become: yes
  name: "Run snap refresh only on webservers"
  tasks:
    - name: "Update ruby gems"
      become: true
      ansible.builtin.shell: snap refresh
