---
- hosts: alpineservers
  serial: 1
  gather_facts: yes
  become: yes
  name: "Run apk commands on all Alpine servers"
  tasks:
    - name: "Update apk index and upgrade all packages"
      community.general.apk:
        update_cache: yes
        upgrade: yes
      register: apk_upgrade

    - name: "Restart services after package upgrades"
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ restart_after_upgrade | default([]) }}"
      when: apk_upgrade is changed
