---
- import_playbook: find_reachable.yaml
  vars:
    target_group: proxmoxservers

- hosts: reachable_proxmoxservers
  gather_facts: yes
  become: yes
  name: "Proxmox: apt upgrade, one host at a time"
  tasks:
    - ansible.builtin.import_tasks: tasks/health_snapshot.yaml

    - name: "Update apt repo and cache on all servers"
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      changed_when: false

    - name: "Upgrade all packages on all servers"
      become: true
      apt:
        upgrade: dist
        force_apt_get: yes
      throttle: 1

    - name: "Remove useless packages from the cache"
      ansible.builtin.apt:
        autoclean: yes

    - name: "Remove dependencies that are no longer required"
      ansible.builtin.apt:
        autoremove: yes

    - name: "Remove dependencies that are no longer required and purge their configuration files"
      ansible.builtin.apt:
        autoremove: yes
        purge: true

    - name: "Run the equivalent of apt-get clean as a separate step"
      apt:
        clean: yes
      changed_when: false

    - ansible.builtin.import_tasks: tasks/health_check.yaml
